/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M17
 * Generated at: 2017-05-29 13:47:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.sql.*;
import com.bridgelab.employeeportal.DBConnection;

public final class EmployeeInfo_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.bridgelab.employeeportal.DBConnection");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');
      out.write('\n');
 
	 DBConnection connect=new DBConnection();
	 Connection connection=connect.getconnection();
//	 request.getRequestDispatcher("Header.jsp").include(request, response);

	 session=request.getSession();
	 Integer user=(Integer) session.getAttribute("userid");
	 if(user!=null)
	 {

      out.write("\t\t<!--  <li class=\"hlie\"><a href=\"Employee\" style = \"padding-left: 50px\">EmployeeRegistration</a><br></li>\n");
      out.write("       </ul>\n");
      out.write("</div> -->\n");
 		try
		{
			PreparedStatement preparedStatement=connection.prepareStatement("Select * from EmployeeDetails where UId=?");
			preparedStatement.setInt(1, user);
			ResultSet resultSet= preparedStatement.executeQuery();

 
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<\n");
      out.write("<link href='http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/themes/redmond/jquery-ui.css' rel='stylesheet' type='text/css'/>\n");
      out.write("<!-- <script src='http://ajax.googleapis.com/ajax/libs/jquery/1.5/jquery.min.js'></script> -->\n");
      out.write("<!-- <script src='http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js'></script> \n");
      out.write(" -->\n");
      out.write("\n");
      out.write(" <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\n");
      out.write("<title>EmployeePortal</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\n");
      out.write("\n");
      out.write("<!-- jQuery library -->\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script> \n");
      out.write("\n");
      out.write("<!-- Latest compiled JavaScript -->\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type='text/javascript'>\n");
      out.write("\n");
      out.write("\t$(document).ready(function () \n");
      out.write("\t{\n");
      out.write("\t\t$('.eli').click(function () \n");
      out.write("\t\t\t\t{\n");
      out.write("\t\t/* \t      var myid=$(this).attr(\"id\");\n");
      out.write("\t\t\t      var ename=$(this).attr(\"name\");\n");
      out.write("\t\t\t      var eaddress=$(this).attr(\"address\");\n");
      out.write("\t\t\t      var ecompany=$(this).attr('company');\n");
      out.write("\t\t\t      var eage=$(this).attr('age');\n");
      out.write("\t\t\t      var egender=$(this).attr('gender');\n");
      out.write("\t\t\t      var especial=$(this).attr('special');\n");
      out.write("\t\t\t      var elang=$(this).attr('lang');\n");
      out.write("\t\t\t      var esalary=$(this).attr('salary');\n");
      out.write("\t\t\t      console.log(myid,'hellllo');\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t$(\"<div class='container'><div title='Information' style='text-align:center'><div><center><form ><table border='2px solid black' ><tr><td>EmpId</td><td>Name</td><td>Address</td><td>Company</td><td>Age</td><td>Gender</td><td>Specialization</td><td>Languages Known</td><td>Salary<br>(in lacs)</td></tr><tr><td>\"+myid+\"</td><td>\"+ename+\"</td><td>\"+eaddress+\"</td><td>\"+ecompany+\"</td><td>\"+eage+\"</td><td>\"+egender+\"</td><td>\"+especial+\"</td><td>\"+elang+\"</td><td>\"+esalary+\"</td></tr></table><br><button name='myid' value='\"+myid+\"'formaction='UpdateDetails' formmethod='post'class='btn btn-primary'>Update</button> <button name='myid' value='\"+myid+\"' formaction='Delete_Emp ' formmethod='post' class='btn btn-danger'>Delete</button></form></center></div></div>\")\n");
      out.write("\t\t\t.dialog({modal: true, height: 200, width: 800 });       */\n");
      out.write("\t//\t\t$(\"#myid\").dialog({modal: true, height: 400, width: 400 });\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t$('#id').val($(this).attr(\"id\"));\t\n");
      out.write("\t\t\t\t$('#pname').val($(this).attr(\"name\"));\n");
      out.write("\t\t\t\t$('#paddress').val($(this).attr(\"address\"));\n");
      out.write("\t\t\t\t$('#pcompany').val($(this).attr(\"company\"));\n");
      out.write("\t\t\t\t$('#page').val($(this).attr(\"age\"));\n");
      out.write("\t\t\t\t$('#pgender').val($(this).attr(\"gender\"));\n");
      out.write("\t\t\t\t$('#pspecial').val($(this).attr(\"special\"));\n");
      out.write("\t\t\t\t$('#plang').val($(this).attr(\"lang\"));\n");
      out.write("\t\t\t\t$('#psalary').val($(this).attr(\"salary\"));\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t$('#myModal').modal({backdrop: true});\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\t}); \n");
      out.write("\t\t    \n");
      out.write("\t});\n");
      out.write("\t</script>\t\n");
      out.write("<style type=\"text/css\">\n");
      out.write("\n");
      out.write(".container{\n");
      out.write("padding-top: 80px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".eul{\n");
      out.write("font-size: 20px;\n");
      out.write("display: block;\n");
      out.write("list-style-type: none;\n");
      out.write("text-align: center;\n");
      out.write("border: 2px solid;\n");
      out.write("padding-left: 0px;\n");
      out.write("\n");
      out.write("\n");
      out.write("}\n");
      out.write(".ecli{\n");
      out.write("border-bottom: 2px solid;\n");
      out.write("padding: 10px;\n");
      out.write("background-color:  #333333;\n");
      out.write("color: white;\n");
      out.write("}\n");
      out.write(".eli{\n");
      out.write("font-size: 15px;\n");
      out.write("padding: 10px;\n");
      out.write("border-bottom: 2px solid;\n");
      out.write("color:white;\n");
      out.write("background-color:  #666666;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".portalname1{\n");
      out.write("color: \t \t #ecf2f9;\n");
      out.write("padding: 8px 15px;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".modal-body{\n");
      out.write("\n");
      out.write("}\n");
      out.write("</style>\t\n");
      out.write("\t\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\t<nav class=\"navbar navbar-inverse navbar-fixed-top\">\n");
      out.write("\t<div class=\"container-fluid\">\n");
      out.write("\t\t<div class=\"navbar-header\">\n");
      out.write("\t\t\t <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\n");
      out.write("        <span class=\"icon-bar\"></span>\n");
      out.write("        <span class=\"icon-bar\"></span>\n");
      out.write("        <span class=\"icon-bar\"></span>                        \n");
      out.write("      </button>\n");
      out.write("         <h4 class=\"portalname1\"><b>EmployeePortal</b></h4>\n");
      out.write("\t\t<!-- \t<a class=\"navbar-brand\" >Employee Portal</a> -->\n");
      out.write("\t\t</div>\n");
      out.write("\t<!-- \t<div class=\"collapse navbar-collapse\"> -->\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" id=\"myNavbar\">\n");
      out.write("\t\t<ul class=\"nav navbar-nav\">\n");
      out.write("\t\t\t");
if(session.getAttribute("userid")!=null) {
      out.write("\n");
      out.write("\t\t\t<li><a href=\"Employee\">EmployeeRegistration</a></li>\n");
      out.write("\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t</ul>\n");
      out.write("\n");
      out.write("\t\t<ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("\t\t\t");
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t");
if(session.getAttribute("userid")!=null){
      out.write("\n");
      out.write("<!-- \t\t\t<li class=\"hli\" style=\"float: right \"><form action=\"Logout\" method=\"post\"  class=\"logout\">\n");
      out.write("<input id=\"hlogout\" type=\"submit\" value=\"Logout\" class=\"btn btn-primary\">  -->\t\t\t\n");
      out.write("\t\t\t<li><a href=\"Logout\">Logout</a></li>\n");
      out.write("\t\t\t");
 }
      out.write("\n");
      out.write("\t\t</ul>\n");
      out.write("\t<!-- \t</div> -->\n");
      out.write("\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t</nav>\n");
      out.write("\n");
      out.write("\t\n");
      out.write("\t\t\t\t\t\n");
      out.write("<div class=\"container\">\n");
      out.write("<div class=\"row\">\n");
      out.write("<div class=\"col-lg-4 col-md-3 col-sm-2\">\n");
      out.write("</div>\n");
      out.write("<div class=\"col-lg-4 col-md-6 col-sm-8\">\n");
      out.write("<!-- <h2> Employee Names</h2> -->\n");
      out.write("\t\t\t\n");
      out.write("            \t <ul class=\"eul\">\n");
      out.write("            \t <li class=\"ecli\"><b>Employee Names</b></li> \n");
      out.write("            ");
 while(resultSet.next())
				{
            
      out.write("\t\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<li class='eli' id=");
      out.print(resultSet.getString(10));
      out.write(" name=\"");
      out.print(resultSet.getString(1));
      out.write("\"\n");
      out.write("\t\t\t\taddress=\"");
      out.print(resultSet.getString(2));
      out.write("\" company=\"");
      out.print(resultSet.getString(3));
      out.write("\" age=");
      out.print(resultSet.getInt(4));
      out.write(" \n");
      out.write("\t\t\t\tgender=");
      out.print(resultSet.getString(5));
      out.write(" special=\"");
      out.print(resultSet.getString(6));
      out.write("\" lang=\"");
      out.print(resultSet.getString(7));
      out.write("\" \n");
      out.write("\t\t\t\tsalary=");
      out.print(resultSet.getInt(9));
      out.write('>');
      out.print(resultSet.getString(1) );
      out.write("</li>\t\n");
      out.write("\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t");
 	}  
      out.write("\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t \n");
      out.write("\t\t");
    }
			  catch (SQLException e) 
			  {
				  e.printStackTrace();
			  }
		  }
				
		  else
		  {
			  response.sendRedirect("Prelogin");
		  }


		  
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("<div class=\"col-lg-4 col-md-3 col-sm-2\">\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("<!-- \t<div title='Information' id='myid' ><table border='2px solid black'><tr><td>EmpId</td><td>Name</td><td>Address</td><td>Company</td><td>Age</td><td>Gender</td><td>Specialization</td><td>Languages Known</td><td>Salary</td></tr><tr></tr></table></div> -->\n");
      out.write("<div class=\"container\">\n");
      out.write(" \n");
      out.write(" \n");
      out.write("  <!-- Modal -->\n");
      out.write("  <div class=\"modal fade\" id=\"myModal\" role=\"dialog\">\n");
      out.write("    <div class=\"modal-dialog\">\n");
      out.write("    \n");
      out.write("      <!-- Modal content-->\n");
      out.write("      <div class=\"modal-content\">\n");
      out.write("        <div class=\"modal-header\">\n");
      out.write("          <button type=\"button\" class=\"close\" data-dismiss=\"modal\">&times;</button>\n");
      out.write("          <h4 class=\"modal-title\">EmployeeInfo</h4>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"modal-body\"><center>\n");
      out.write("        <form >\n");
      out.write("        <table class=\"table\">\n");
      out.write("        <tr><td><label>Employee ID </label></td>\n");
      out.write("          <td><input type=\"text\" id=\"id\" readonly=\"readonly\"></td>\n");
      out.write("         </tr> \n");
      out.write("         <tr><td><label>Name</label></td>\n");
      out.write("          <td><input type=\"text\" id=\"pname\" readonly=\"readonly\"></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr><td><label> Address </label></td>\n");
      out.write("          <td><input type=\"text\" id=\"paddress\" readonly=\"readonly\"></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr><td><label>Company </label></td>\n");
      out.write("          <td><input type=\"text\" id=\"pcompany\" readonly=\"readonly\"></td>\n");
      out.write("         </tr>\n");
      out.write("         <tr><td><label>Age </label></td>\n");
      out.write("          <td><input type=\"text\" id=\"page\" readonly=\"readonly\"></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr><td><label>Gender </label></td>\n");
      out.write("          <td><input type=\"text\" id=\"pgender\" readonly=\"readonly\"></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr><td><label>Specialization </label></td>\n");
      out.write("          <td><input type=\"text\" id=\"pspecial\" readonly=\"readonly\"></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr><td><label>Languages</label></td>\n");
      out.write("          <td><input type=\"text\" id=\"plang\" readonly=\"readonly\"></td>\n");
      out.write("          </tr>\n");
      out.write("          <tr><td><label>Salary </label></td>\n");
      out.write("          <td><input type=\"text\" id=\"psalary\" readonly=\"readonly\"></td>\n");
      out.write("          </tr>\n");
      out.write("        </table>\n");
      out.write("        </form>\n");
      out.write("        </center>\n");
      out.write("        </div>\n");
      out.write("        <div class=\"modal-footer\">\n");
      out.write("        <form action=\"UpdateDetails\" method=\"post\">\n");
      out.write("        \t<input type=\"hidden\" id=\"id\" name=\"myid\">\n");
      out.write("          <button  class=\"btn btn-default\"    data-dismiss=\"modal\">Close</button>\n");
      out.write("          <input type=\"submit\" value=\"Update\" id=\"id\" name=\"myid\">\n");
      out.write("          <!-- <button  class=\"btn btn-info btn-md\" id=\"id\" formaction=\"UpdateDetails\" method=\"post\" >Update</button>-->\n");
      out.write("            <button  class=\"btn btn-info btn-md\" id=\"id\" formaction=\"Delete_Emp\" method=\"post\">Delete</button>\n");
      out.write("        </form>\n");
      out.write("        </div>\n");
      out.write("      </div>\n");
      out.write("      \n");
      out.write("    </div>\n");
      out.write("  </div>\n");
      out.write("  </div>\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
