/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M17
 * Generated at: 2017-05-29 07:55:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import java.sql.*;
import com.bridgelab.employeeportal.DBConnection;

public final class Update_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/header.jsp", Long.valueOf(1495861497000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.bridgelab.employeeportal.DBConnection");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');
      out.write('\n');

	 DBConnection connect=new DBConnection();
	 Connection connection=connect.getconnection();
//	 request.getRequestDispatcher("Header.jsp").include(request, response);

	 session=request.getSession();
	 Integer user=(Integer) session.getAttribute("userid");
	 String empid=(String)session.getAttribute("eid");
	 if(user!=null)
	 {
    	try
		{
			PreparedStatement preparedStatement=connection.prepareStatement("Select * from EmployeeDetails where empid=?");
			preparedStatement.setString(1, empid);
			ResultSet rs= preparedStatement.executeQuery();

 
      out.write('\n');
      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write(" <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\n");
      out.write("<title>EmployeePortal</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\n");
      out.write("\n");
      out.write("<!-- jQuery library -->\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- Latest compiled JavaScript -->\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\n");
      out.write("<style>\n");
      out.write(".portalname{\n");
      out.write("color: \t \t #ecf2f9;\n");
      out.write("padding: 8px 15px;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<nav class=\"navbar navbar-inverse navbar-fixed-top\">\n");
      out.write("\t<div class=\"container-fluid\">\n");
      out.write("\t\t<div class=\"navbar-header\">\n");
      out.write("\t\t ");
if(session.getAttribute("userid")!=null) {
      out.write("\n");
      out.write("\t\t  <button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\" data-target=\"#myNavbar\">\n");
      out.write("             <span class=\"icon-bar\"></span>\n");
      out.write("             <span class=\"icon-bar\"></span>\n");
      out.write("             <span class=\"icon-bar\"></span>                        \n");
      out.write("          </button>\n");
      out.write("        ");
} 
      out.write("\n");
      out.write("        <h4 class=\"portalname\"><b>EmployeePortal</b></h4>\n");
      out.write("\t<!-- \t\t<a class=\"navbar-brand\" >Employee Portal</a> -->\n");
      out.write("\t    </div>\n");
      out.write("\t\n");
      out.write("\t\t<div class=\"collapse navbar-collapse\" id=\"myNavbar\">\n");
      out.write("\t\t<ul class=\"nav navbar-nav\">\n");
      out.write("\t\t\t");
if(session.getAttribute("userid")!=null) {
      out.write("\n");
      out.write("\t\t\t<li><a href=\"EmployeeDetails\">EmployeeDetails</a></li>\n");
      out.write("\t\t\t");
} 
      out.write("\n");
      out.write("\t\t\t\n");
      out.write("\t\t</ul>\n");
      out.write("\n");
      out.write("\t\t <ul class=\"nav navbar-nav navbar-right\">\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t");
if(session.getAttribute("userid")!=null){
      out.write("\n");
      out.write("<!-- \t\t  <li class=\"hli\" style=\"float: right \"><form action=\"Logout\" method=\"post\"  class=\"logout\">\n");
      out.write("               <input id=\"hlogout\" type=\"submit\" value=\"Logout\" class=\"btn btn-primary\">  -->\t\t\t\n");
      out.write("\t\t\t  <li><a href=\"Logout\">Logout</a></li>\n");
      out.write("\t\t\t");
 }
      out.write("\n");
      out.write("\t\t </ul>\n");
      out.write("\t\n");
      out.write("       </div>\n");
      out.write("\t</div>\n");
      out.write("\t</nav>\n");
      out.write("</body>");
      out.write("\n");
      out.write("<!-- <li class=\"hlid\"><a href=\"EmployeeDetails\" style=\"padding-left: 30px\">EmployeeDetails</a><br></li>\n");
      out.write("\t</ul>\n");
      out.write("</div> -->\n");
      out.write("<!-- <!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\"> -->\n");


	while(rs.next())
	{	

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write(" <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("\n");
      out.write("<title>EmployeePortal</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\n");
      out.write("\n");
      out.write("<!-- jQuery library -->\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n");
      out.write("\n");
      out.write("<!-- Latest compiled JavaScript -->\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\n");
      out.write("\n");
      out.write("function validateemp()\n");
      out.write("{\n");
      out.write("\n");
      out.write("\tvar fullname=document.getElementById('ename').value;\n");
      out.write("\tvar name = /^[a-zA-Z  ]+$/;\n");
      out.write("\t\n");
      out.write(" \tif(fullname.length==null ||!name.test(fullname))\n");
      out.write(" \t{\n");
      out.write(" \t\talert(\"Enter Name which contains only alphabets \");\n");
      out.write(" \t\treturn false;\n");
      out.write(" \t\t\n");
      out.write(" \t}\n");
      out.write(" \tif($('#eadd').val()==null || $('#eadd').val()==\"\")\n");
      out.write("  \t{\n");
      out.write("\t\t alert(\"Please Enter Address\");\n");
      out.write("\t\t return false;\n");
      out.write("     }\t\n");
      out.write(" \t\n");
      out.write(" \tif($('#cname').val()==null || $('#cname').val()==\"\")\n");
      out.write("  \t{\n");
      out.write("\t\t alert(\"Please Enter Company name\");\n");
      out.write("\t\t return false;\n");
      out.write("     }\t\n");
      out.write(" \t\n");
      out.write(" \tvar eage=document.getElementById('num').value;\n");
      out.write(" \t\n");
      out.write(" \tif($('#num').val()>100 || $('#num').val()<1)\n");
      out.write(" \t{\n");
      out.write(" \t\talert(\"Enter valid age\");\n");
      out.write(" \t\treturn false;\n");
      out.write(" \t\t\n");
      out.write(" \t}\t\n");
      out.write(" \tvar esall=document.getElementById('num1').value;\n");
      out.write(" \tif($('#num1').val()>1000 || $('#num1').val()<0)\n");
      out.write(" \t{\n");
      out.write(" \t\talert(\"Enter valid salary (0-1000)\");\n");
      out.write(" \t\treturn false;\n");
      out.write(" \t\t\n");
      out.write(" \t}\n");
      out.write(" \t\n");
      out.write("  \tvar spec=document.getElementById('specializeU').value;\n");
      out.write(" \tif(spec.length==null ||!name.test(spec))\n");
      out.write(" \t{\n");
      out.write(" \t\talert(\"Enter specialization \");\n");
      out.write(" \t\treturn false;\n");
      out.write(" \t\t\n");
      out.write(" \t}\n");
      out.write("\n");
      out.write(" \t/* var lng=document.getElementById('languageU').value;\n");
      out.write(" \tif(lng.length==null ||!name.test(lng))\n");
      out.write(" \t{\n");
      out.write(" \t\talert(\"Enter Languages \");\n");
      out.write(" \t\treturn false;\n");
      out.write(" \t\t\n");
      out.write(" \t} */\n");
      out.write(" \tvar laung=document.empupdtn.language;\n");
      out.write(" \tfor(var i=0;i<laung.length;i++)\n");
      out.write(" \t{\n");
      out.write(" \t\tif(laung[i].checked)\n");
      out.write(" \t\t\tbreak;\n");
      out.write(" \t\telse \n");
      out.write(" \t\talert(\"Please select Language\");\n");
      out.write(" \t\treturn false;\n");
      out.write(" \t}\t\n");
      out.write(" \t\n");
      out.write("}\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("<style type=\"text/css\">\n");
      out.write("\n");
      out.write(".container{\n");
      out.write("margin-top: 80px;\n");
      out.write("\n");
      out.write("}\n");
      out.write(" #empup{\n");
      out.write("border: 2px solid black;\n");
      out.write("\n");
      out.write("background-color: #f0f5f5;\n");
      out.write("padding-bottom: 40px;\n");
      out.write("padding-top: 10px;\n");
      out.write("padding-left: 20px;\n");
      out.write("padding-right: 20px;\n");
      out.write("}\n");
      out.write("} \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("<div class=\"container\">\n");
      out.write("<div class=\"row\">\n");
      out.write("<div class=\"col-lg-4 col-md-3 col-sm-2\">\n");
      out.write("</div>\n");
      out.write("<div class=\"col-lg-4 col-md-6 col-sm-8\" id=\"empup\">\n");
      out.write("<h2>  Update EmployeeDetails </h2>\n");
      out.write("  <form action=\"Update_Emp\"method=\"post\" onsubmit=\"return validateemp()\"  name=\"empupdtn\">\n");
      out.write("\t\t\n");
      out.write("  \n");
      out.write("    <div class=\"form-group\">\n");
      out.write("      <label  >Employee Name</label>\n");
      out.write("      <input type=\"text\" id=\"ename\" placeholder=\"Enter  name\" name=\"name\" value=\"");
      out.print(rs.getString(1));
      out.write("\" required>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div class=\"form-group\">\n");
      out.write("      <label id=\"addid\" >Address</label>\n");
      out.write("       <textarea  rows=\"3\" id=\"eadd\"  placeholder=\"Enter Address\" name=\"address\" required   style=\"margin-left:50px\">");
      out.print(rs.getString(2));
      out.write("</textarea>\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div class=\"form-group\">\n");
      out.write("      <label  >Company Name</label>\n");
      out.write("     <input type=\"text\" id=\"cname\" placeholder=\"Enter company name\" name=\"company\" value=\"");
      out.print(rs.getString(3));
      out.write("\" required >\n");
      out.write("    </div>\n");
      out.write("     <div class=\"form-group\">\n");
      out.write("      <label >Age</label>\n");
      out.write("      <input type=\"number\" id=\"num\"placeholder=\"Enter Age\" name=\"age\"   value=");
      out.print(rs.getInt(4));
      out.write(" style=\"margin-left:80px\" required>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"form-group\">\n");
      out.write("      <label >Salary</label>\n");
      out.write("      <input type=\"number\" id=\"num1\"placeholder=\"Enter Salary\" name=\"salary\" required style=\"margin-left:65px\" value=\"");
      out.print(rs.getString(9));
      out.write("\">\n");
      out.write("    </div>\n");
      out.write("    <div class=\"form-group\">\n");
      out.write("      <label >Gender</label>\n");
      out.write("      ");
if(rs.getString(5).equals("male")) {
      out.write("\n");
      out.write("      <input type=\"radio\" name=\"gender\" value=\"male\"  checked style=\"margin-left:50px\">Male &nbsp &nbsp\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"gender\" value=\"female\">Female\n");
      out.write("\t\t");
} else{ 
      out.write("\n");
      out.write("\t\t<input type=\"radio\" name=\"gender\" value=\"male\" style=\"margin-left:50px\">Male &nbsp &nbsp\n");
      out.write("\t\t\t\t<input type=\"radio\" name=\"gender\" value=\"female\"  checked>Female\t\n");
      out.write("\t\t\t\t");
} 
      out.write("\t\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    <div class=\"form-group\">\n");
      out.write("      <label  >Specialization</label>\n");
      out.write("     <input type=\"text\" id=\"specializeU\" placeholder=\"Enter specialization\" name=\"special\" value=\"");
      out.print(rs.getString(6));
      out.write("\" style=\"margin-left:30px\"  >\n");
      out.write("    </div>\n");
      out.write("    <div class=\"form-group\">\n");
      out.write("      <label >Languages Known</label>\n");
      out.write("      <input type=\"text\" id=\"languageU\" placeholder=\"Enter Languages \" name=\"lang\" value=\"");
      out.print(rs.getString(7));
      out.write("\" required >\n");
      out.write("    </div>\n");
      out.write("    \n");
      out.write("    \n");
      out.write("    \n");
      out.write("    \n");
      out.write("    \n");
      out.write("    \n");
      out.write("    \n");
      out.write("   <div class=\"form-group\">\n");
      out.write("    <input type=\"submit\" value=\"Update\"  class=\"btn btn-success btn-block\" \n");
      out.write("\t\t\t\t\t\t\t\tonclick=\"return validateemp()\">\n");
      out.write("\t\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"form-group\">\n");
      out.write("\t<button formaction=\"EmployeeDetails\" class=\"btn btn-primary btn-block\">Cancel\t</button>\n");
      out.write("    </div>\n");
      out.write("  </form>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("<div class=\"col-lg-4 col-md-3 col-sm-2\">\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    }
	}	
	catch (SQLException e) 
			  {
				  e.printStackTrace();
			  }
		  }
				
		  else
		  {
			  response.sendRedirect("Prelogin");
		  }


		  
      out.write("\n");
      out.write("\t\t  \n");
      out.write("\t\t  \n");
      out.write("\t\t  \n");
      out.write("\t\t  \n");
      out.write("\t\t  \n");
      out.write("\t\t  \n");
      out.write("\t\t  \n");
      out.write("\t\t  ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
